### ISSUE TITLE
Usage docs

### ISSUE THREAD

**Issue by joncison** [edamontology/edammap#1]
We need a manual, usage docs or some such

**Comment by ufli** [comment]
Is there any chance that the manual will appear in the nearest future? Would like to test the tool and have no idea how to get the working version.

**Comment by bug1303** [comment]
EDIT: I just found the fork by Ahto123, so there's at least a quick 'how-to' and the thesis with more elaborate methods description. Of course it could be brushed upon and some actually valid sample files should be in the examples folder, but I can work with this for now. Thanks @Ahto123

~~Any plans (time frame) of adding those?~~
~~I tried creating some queries, but failed to match the expected format apparently, also couldn't get it to work with the included example files.~~
~~No matter what I tried so far, I get :~~

~~Start~~
~~Loading concepts~~
~~SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".~~
~~SLF4J: Defaulting to no-operation (NOP) logger implementation~~
~~SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.~~
~~Processing concepts~~
~~Loading queries~~
~~java.text.ParseException: "Name" column missing or some entry in that column missing! (2)~~


~~While it might be ok to ignore the logging warning, I would be happy to see an example of how input should look like, especially the case were input is a short text/publication abstract. But also how manually curated input should look like to create benchmark reports.~~
~~From the parameter described by the help output, it seems a lot of thought and work has been put in it. To be able to test it, I'd prefer a short how-to run instead of having to reverse engineer from the code... :)~~

**Comment by joncison** [comment]
can you point me to the 'how-to' and thesis please ?

**Comment by ahtosalumets** [comment]
I attached thesis and tutorial, if I understand correctly, someone has
deleted the docs?


All the best,
Ahto

**Comment by joncison** [comment]
I'm not sure ... anyhow, the docs should be in the repo please, if you can reinstate them

**Comment by bug1303** [comment]
You just have to pull in the changes from the fork, see :  https://github.com/edamontology/edammap/network 

https://github.com/Ahto123/edammap is  2 commits ahead of edamontology:master

**Comment by joncison** [comment]
ahh ... I was waiting for the pull request.  When you make one, I will do it.

**Comment by bug1303** [comment]
This one can be closed, the documentation folder, with the full thesis, a quick how-to, and some simple example input has been added to the repo. 
It could be extended with instructions on how to build from src though.

**Comment by joncison** [comment]
Thanks!
