### ISSUE TITLE
mismatch example.csv and csv parser settings

### ISSUE THREAD

**Issue by bug1303** [edamontology/edammap#3]
The provided example.csv uses single quotes around the description. However, the parser expects double quotes. This is true for the 0.1.1 release as well as the current latest commit.

For the 0.1.1 version, this has actually been previously fixed by:
https://github.com/Ahto123/edammap/commit/f6ea9223546c94774adb098d03682d4170718447
but never merged into the release/master branch.

For the current master branch, a different edit is required (in the same file though): 

```
edammapper/src/main/java/edammapper/input/Csv.java

@@ -43 +43 @@ public class Csv {
-               settings.getFormat().setQuote('"');
+               settings.getFormat().setQuote('\'');
```
and possibly also adjust setQuoteEscape and setCharToEscapeQuoteEscaping (see https://github.com/uniVocity/univocity-parsers#escaping-quote-escape-characters).

Alternatively, it could be settled on using double quotes, keep the code unchanged, and instead adjust example.csv and the tutorial accordingly.

**Comment by jaanisoe** [comment]
I think double quotes are more common, e.g.
https://www.w3.org/TR/tabular-data-model/#lines

Ahto changed to single quotes, because he had a parsing problem with double quotes at some point, but we couldn't figure out what it was. Also, I've changed the CSV library (opencsv → uniVocity) since then.

So I would suggest keeping double quotes for now and updating the documentation.

**Comment by jaanisoe** [comment]
Settled on double quotes, example and documentation are updated accordingly.
